apiVersion: apps/v1
kind: Deployment
metadata:
  name: position-tracker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: position-tracker
  template:
    metadata:
      labels:
        app: position-tracker
    spec:
      containers:
        - name: position-tracker
          image: richardchesterwood/k8s-fleetman-position-tracker:release4
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: production-microservice
          resources:
            requests:
              memory: 200Mi
              cpu: 50m
