apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
data:
  accessKey: MTIzNDU2Nzg5MAo=
  secretKey: U0VDUkVUMTIzNAo=
stringData:
  accessKeyPlain: "1234567890"
  secretKeyPlain: "SECRET1234"