apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: put-specific-user-or-users-into-new-joiner-role
  namespace: default
subjects:
# List users that are going into this role
- kind: User
  name: francis-linux-login-name
roleRef:
  kind: Role
  name: new-joiner
  apiGroup: rbac.authorization.k8s.io
